name: ctcOpen
description: Open a CTC case for a release

inputs:
  SF_CHANGE_CASE_SFDX_AUTH_URL:
    description: Auth URL
    required: true
  SF_CHANGE_CASE_TEMPLATE_ID:
    description: Change Case template ID
    required: true
  SF_CHANGE_CASE_CONFIGURATION_ITEM:
    description: Change Case config item
    required: true
  SVC_CLI_BOT_GITHUB_TOKEN:
    description: Github token
    required: true

outputs:
  changeCaseId:
    description: Id for the change case created
    value: ${{ steps.ctc.outputs.ctcResult }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.SVC_CLI_BOT_GITHUB_TOKEN }}

    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: npm

    - run: npm install -g @salesforce/change-case-management --omit=dev
      shell: bash

    - name: Open CTC case
      id: ctc
      uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd
      with:
        max_attempts: 5
        retry_wait_seconds: 60
        timeout_minutes: 60
        command: |
          CTC_RESULT=$(sfchangecase create --location ${{github.repositoryUrl}} --release ${{github.repository}}.$(date +%F) --json | jq -r '.result.id')
          echo "ctcResult=$CTC_RESULT" >> "$GITHUB_OUTPUT"
      env:
        SF_CHANGE_CASE_SFDX_AUTH_URL: ${{ inputs.SF_CHANGE_CASE_SFDX_AUTH_URL}}
        SF_CHANGE_CASE_TEMPLATE_ID: ${{ inputs.SF_CHANGE_CASE_TEMPLATE_ID}}
        SF_CHANGE_CASE_CONFIGURATION_ITEM: ${{ inputs.SF_CHANGE_CASE_CONFIGURATION_ITEM}}

    - run: echo "case id is ${{ steps.ctc.outputs.ctcResult }}"
      shell: bash
