# This action is only needed as long as the developer site and other docs are linking to the old sfdx.pkg file and the mac signing job is only signing the old file as well.
# It can be deleted once those are updated to use the new name, sfdx-x64.pkg.
name: rename-mac-pkg
description: renames the intel mac pkg file created by oclif v3 to match the name of the file created by oclif v2

inputs:
  cli: 
    description: which CLI to rename the pkg file for (e.g. sfdx or sf)
    required: true
  channel:
    description: cli channel to target (e.g. stable, stable-rc)
    required: true

runs:
  using: "composite"
  steps:
    - id: download-and-rename-x64-pkg
      shell: bash
      run: aws s3 cp s3://dfc-data-production/media/salesforce-cli/${{ inputs.cli }}/channels/${{ inputs.channel }}/sfdx-x64.pkg ./sfdx.pkg
    - id: upload-renamed-pkg
      shell: bash
      run: aws s3 cp ./sfdx.pkg s3://dfc-data-production/media/salesforce-cli/${{ inputs.cli }}/channels/${{ inputs.channel }}/
