on:
  workflow_call:
    outputs:
      changeCaseId:
        description: Id for the change case created
        value: ${{ jobs.ctcOpen.outputs.changeCaseId }}

jobs:
  ctcOpen:
    outputs:
      changeCaseId: ${{ steps.ctc.outputs.ctcResult }}
    runs-on: static-ip-ubuntu-runners
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm install -g @salesforce/change-case-management --omit=dev
      - name: Open CTC case
        id: ctc
        uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd
        with:
          max_attempts: 5
          retry_wait_seconds: 60
          timeout_minutes: 60
          command: |
            CTC_RESULT=$(sfchangecase create --location ${{github.repositoryUrl}} --release ${{github.repository}}.$(date +%F) --json | jq -r '.result.id')
            echo "ctcResult=$CTC_RESULT" >> "$GITHUB_OUTPUT"
        env:
          SF_CHANGE_CASE_SFDX_AUTH_URL: ${{ secrets.SF_CHANGE_CASE_SFDX_AUTH_URL}}
          SF_CHANGE_CASE_TEMPLATE_ID: ${{ secrets.SF_CHANGE_CASE_TEMPLATE_ID}}
          SF_CHANGE_CASE_CONFIGURATION_ITEM: ${{ secrets.SF_CHANGE_CASE_CONFIGURATION_ITEM}}
      - run: echo "case id is ${{steps.ctc.outputs.ctcResult}}"
