on:
  workflow_call:

jobs:
  # is there already a PR open?
  checkPRs:
    outputs:
      shouldUpdate: ${{ !contains(steps.currentOpenPRs.outputs.alreadyOpen, 'devScripts update') }}
    runs-on: ubuntu-latest
    steps:
      - id: currentOpenPRs
        run: echo "::set-output name=alreadyOpen::$(gh pr list -R ${{ github.repository }})"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "command output - ${{steps.currentOpenPRs.outputs.alreadyOpen}}"
      - run: echo "should open - ${{ !contains(steps.currentOpenPRs.outputs.alreadyOpen, 'devScripts update' )}}"
  # what is the RC version, numerically?
  compareVersions:
    needs: [checkPRs]
    if: ${{ needs.checkPRs.outputs.shouldUpdate == 'true' }}
    outputs:
      shouldUpdate: ${{ !endsWith(steps.packageVersion.outputs.prop, steps.version-info.outputs.version) }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: salesforcecli/github-workflows/.github/actions/versionInfo@main
        id: version-info
        with:
          version: latest
          npmPackage: "@salesforce/dev-scripts"
      - run: echo "dev scripts latest is ${{ steps.version-info.outputs.version }}"
      - uses: notiz-dev/github-action-json-property@2192e246737701f108a4571462b76c75e7376216
        id: packageVersion
        with:
          path: "package.json"
          prop_path: "devDependencies.@salesforce/dev-scripts"

      - run: echo "this repo has version is ${{ steps.packageVersion.outputs.prop }}"
      - run: echo "output value will be ${{ !endsWith(steps.packageVersion.outputs.prop, steps.version-info.outputs.version) }}"

  updateDevScripts:
    needs: [compareVersions]
    if: ${{ needs.compareVersions.outputs.shouldUpdate == 'true' }}
    runs-on: "ubuntu-latest"
    steps:
      - run: echo "previous job output was ${{ needs.compareVersions.outputs.shouldUpdate }}"
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
      - uses: salesforcecli/github-workflows/.github/actions/gitConfig@main

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: npm install -g yarn-deduplicate
      - run: yarn upgrade @salesforce/dev-scripts@latest
      # this may fail because that's how dev-scripts does things
      - run: yarn install  --network-timeout 600000
        continue-on-error: true

      - run: yarn install  --network-timeout 600000
      - run: npx yarn-deduplicate
      - run: yarn install  --network-timeout 600000
        # clean up any outstanding unmerged devScripts PRs
      - run: |
          PRs=$(gh pr list --search "in:title devScripts update" --json number | jq '.[] | .number' -r | tr -d '[],"')
          for pr in $PRs; do
              gh pr close "$pr" -c "will be replaced with new PR" --delete-branch
          done
      # this may fail but we still want a PR with partial fix
      - run: |
          git checkout -b devScripts$(date +%F)
          yarn lint --fix
        continue-on-error: true
      - run: |
          git add .
          git commit -m 'chore: updates from devScripts' --no-verify
          git push origin --no-verify
          sleep 60
          gh pr create --title 'refactor: devScripts update' --body 'created via github action [skip-validate-pr]' -l dependencies
        env:
          GH_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
