on:
  workflow_call:
    inputs:
      command:
        required: false
        type: string
        default: yarn test:nuts
        description: "command to execute (ex: yarn test:nuts)"
      nodeVersion:
        required: false
        description: version of node to run tests against.  Use things like [lts/-1, lts/*, latest] to avoid hardcoding versions
        type: string
        default: lts/*
      os:
        required: false
        description: "runs-on property, ex: ubuntu-latest, windows-latest"
        type: string
        default: "ubuntu-latest"
      sfdxExecutablePath:
        required: false
        description: "Path to sfdx executable to be used by NUTs, defaults to ''"
        type: string
      useCache:
        required: false
        type: boolean
        default: true

jobs:
  nut:
    env:
      TESTKIT_AUTH_URL: ${{ secrets.TESTKIT_AUTH_URL}}
      TESTKIT_HUB_USERNAME: ${{ secrets.TESTKIT_HUB_USERNAME }}
      TESTKIT_JWT_CLIENT_ID: ${{ secrets.TESTKIT_JWT_CLIENT_ID }}
      TESTKIT_JWT_KEY: ${{ secrets.TESTKIT_JWT_KEY }}
      TESTKIT_HUB_INSTANCE: ${{ secrets.TESTKIT_HUB_INSTANCE }}
      ONEGP_TESTKIT_AUTH_URL: ${{ secrets.ONEGP_TESTKIT_AUTH_URL }}
    name: ${{ inputs.command }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: salesforcecli/github-workflows/.github/actions/windowsCachePerf@yarn-global-install
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: yarn
      # dynamically get the os-specific locations for the yarn global installs of the CLI
      - run: echo "{yarnGlobalDir}=yarn global dir" >> $GITHUB_OUTPUT
        id: yarnGlobalDir
      - run: echo "{yarnGlobalBin}=yarn global bin" >> $GITHUB_OUTPUT
        id: yarnGlobalBin
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Cache yarn globals
        id: cache-yarnGlobals
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn-globals
        with:
          path: |
            ${{ steps.yarnGlobalDir.outputs.yarnGlobalDir}}
            ${{ steps.yarnGlobalBin.outputs.yarnGlobalBin}}
          key: ${{ runner.os }}-${{ env.cache-name }}
      - run: yarn global add sfdx-cli @salesforce/cli
        if: ${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}
      - run: yarn install --network-timeout 600000
        if: ${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}

      - run: yarn compile
      - run: ${{ inputs.command }}
        if: inputs.sfdxExecutablePath != ''
        env:
          TESTKIT_EXECUTABLE_PATH: ${{ inputs.sfdxExecutablePath }}
      - run: ${{ inputs.command }}
        if: inputs.sfdxExecutablePath == ''
