on:
  workflow_call:
    inputs:
      cli:
        type: string
        required: true
        description: only needed if upload. sfdx or sf
      version:
        type: string
        required: true
        description: version for upload. do not include the 'v'
      channel:
        type: string
        required: true
        description: channel that the uploaded tarballs get promoted to

jobs:
  macos:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SFDX_HIDE_RELEASE_NOTES: true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install  --network-timeout 600000
      # todo: download the macos tarball and pass that to the oclif pack:macos command
      - run: yarn pack:macos
      - run: yarn upload:macos
      - run: yarn channel:promote --cli ${{ inputs.cli }} --version ${{ inputs.version }} --target ${{ inputs.channel }} --platform macos
        name: Promote macos to ${{ inputs.channel }} channel
  # The rename-mac-pkg job is only needed as long as the developer site is linking to the old sfdx.pkg file and the mac signing job is only signing the old file as well.
  # It can be removed once those are updated to use the new name, sfdx-x64.pkg.
  rename-mac-pkg:
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-cli:2.8.6
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EC2_METADATA_DISABLED: true
    needs: [macos]
    steps:
      - run: aws s3 cp s3://dfc-data-production/media/salesforce-cli/${{ inputs.cli }}/channels/${{ inputs.channel }}/sfdx-x64.pkg ./sfdx.pkg
      - run: aws s3 cp ./sfdx.pkg s3://dfc-data-production/media/salesforce-cli/${{ inputs.cli }}/channels/${{ inputs.channel }}/
