on:
  workflow_call:

jobs:
  prevent-typescript-dependency:
    uses: salesforcecli/github-workflows/.github/workflows/preventTypescriptDep.yml@wr/noTS
  linux-unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsLinux.yml@main
  windows-unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsWindows.yml@main
