on:
  workflow_call:

jobs:
  unit-tests:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        # node_version: [lts/-1, lts/*, latest]
        node_version: [lts/-1, lts/*]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - run: yarn install  --network-timeout 600000
        if: ${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}
      - run: yarn build
      - run: yarn test
  lockfile-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: |
          npm install -g lockfile-lint
          lockfile-lint --path yarn.lock --allowed-hosts npm yarn --validate-https
